# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: install makeobj
        shell: pwsh
        run: |
          wget -O makeobj.zip https://master.dl.sourceforge.net/project/simutrans/makeobj/60-5%20for%20122-0%20up/makeobj-win-60-5.zip?viasf=1
          Expand-Archive makeobj.zip

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8"

      - name: Composer Install
        run: composer install

      - name: Test
        run: ./vendor/bin/phpunit.bat -v

  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install makeobj via apt
        run: sudo apt install -y simutrans-makeobj

      - name: chmod
        run: chmod -R 777 ./

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8"

      - name: Composer Install
        run: composer install

      - name: Test
        run: ./vendor/bin/phpunit -c phpunit.linux.xml -v
