# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install makeobj dependencies
        run: apt-get install -y libpng-dev
      - name: check makeojb dependencies
        run: ldd ./bin/makeobj-linux-60-2/makeobj

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Composer Install
        run: composer install
      - name: Test
        run: ./vendor/bin/phpunit -c phpunit.linux.xml
